import fs from 'node:fs';
import path from 'node:path';
// The deployed bundle must include refreshed static theme routes when place availability changes.
await import('./refresh-theme-route-changes.mjs');
await import('./verify-theme-route-updates.mjs');
const root=fs.realpathSync('.');
const output=path.resolve(root,'dist');
if(path.dirname(output)!==root || path.basename(output)!=='dist') throw Error('Unsafe output path');
fs.rmSync(output,{recursive:true,force:true});
fs.mkdirSync(path.join(output,'server'),{recursive:true});
fs.mkdirSync(path.join(output,'.openai'),{recursive:true});
fs.cpSync('public',path.join(output,'client'),{recursive:true});
const data=JSON.parse(fs.readFileSync('public/places.json','utf8')).places;
data.push(...JSON.parse(fs.readFileSync('public/gangneung-places.json','utf8')).places);
data.push(...JSON.parse(fs.readFileSync('public/gyeongju-places.json','utf8')).places);
data.push({id:'station',lat:34.7914,lon:126.3859});
data.push({id:'gangneung-station',lat:37.7641331,lon:128.8997106});
data.push({id:'gyeongju-station',lat:35.7983772522824,lon:129.138999419567});
const points=Object.fromEntries(data.filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon)).map(p=>[p.id,[p.lon.toFixed(7),p.lat.toFixed(7)]]));
const source=fs.readFileSync('worker/index.js','utf8').replace('/* REGISTERED_POINTS */ {}',JSON.stringify(points));
fs.writeFileSync(path.join(output,'server/index.js'),source);
fs.copyFileSync('.openai/hosting.json',path.join(output,'.openai/hosting.json'));
console.log('Built latest UI, address search, registered-only route persistence.');
